-- Seed sample products for Namak Halal

INSERT INTO products (name, slug, description, short_description, price, compare_at_price, category, shape, size, weight_kg, stock_quantity, is_featured, images, usage_instructions, safety_notes) VALUES
(
  'Natural Himalayan Salt Lamp - Medium',
  'natural-himalayan-salt-lamp-medium',
  'Hand-carved from authentic Khewra salt mine crystals, this medium-sized lamp creates a warm, amber glow that transforms any space. Each lamp is unique, featuring natural variations in color and texture that reflect millions of years of geological formation. Perfect for bedrooms, living rooms, or meditation spaces.',
  'Hand-carved authentic Khewra salt lamp with warm amber glow',
  4500.00,
  5500.00,
  'salt-lamp',
  'Natural',
  'Medium',
  2.5,
  50,
  true,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Place on a stable surface away from moisture. Use the included E14 15W bulb or lower wattage for a softer glow. Leave on for 4-6 hours daily to enjoy full benefits.',
  'Keep away from water and high humidity. Use only approved bulb wattages. Ensure proper ventilation around the lamp. Not recommended for bathrooms.'
),
(
  'Pyramid Salt Lamp',
  'pyramid-salt-lamp',
  'Geometrically carved into a perfect pyramid shape, this unique lamp combines ancient sacred geometry with the natural healing properties of Himalayan pink salt. The pyramid shape is believed to amplify energy and create a focal point of positive vibrations in your space.',
  'Sacred geometry meets natural healing in this pyramid-shaped lamp',
  5500.00,
  6500.00,
  'salt-lamp',
  'Pyramid',
  'Medium',
  3.0,
  30,
  true,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Display on a flat surface in a dry area. The pyramid shape directs light upward, making it ideal for corner placements or as a centerpiece.',
  'Handle with care - geometric shapes have precise edges. Keep away from moisture and direct sunlight.'
),
(
  'Sphere Salt Lamp',
  'sphere-salt-lamp',
  'Perfectly rounded and polished, this sphere salt lamp offers a 360-degree glow that radiates warmth evenly throughout your space. The smooth surface showcases the beautiful pink and orange hues of authentic Himalayan salt, creating a stunning visual centerpiece.',
  'Perfectly polished sphere with 360-degree warm glow',
  6500.00,
  7500.00,
  'salt-lamp',
  'Sphere',
  'Medium',
  3.5,
  25,
  true,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'The sphere sits on an included wooden base. Rotate occasionally for even light distribution. Ideal for living rooms and common areas.',
  'Handle carefully due to weight. Ensure the wooden base is stable before placing the sphere.'
),
(
  'USB Mini Salt Lamp',
  'usb-mini-salt-lamp',
  'Perfect for your desk or bedside table, this compact USB-powered salt lamp brings the benefits of Himalayan salt to your workspace. No electrical outlet needed - simply plug into any USB port for a gentle, soothing glow during work or rest.',
  'Compact USB-powered lamp perfect for desks and nightstands',
  1500.00,
  2000.00,
  'salt-lamp',
  'Natural',
  'Mini',
  0.5,
  100,
  false,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Connect to any USB port (computer, power bank, or adapter). LED bulb included - no heat generation. Perfect for continuous use.',
  'Do not expose to water. USB cable should not be bent or damaged. Keep away from liquids on your desk.'
),
(
  'Heart Shape Salt Lamp',
  'heart-shape-salt-lamp',
  'Express love and warmth with this beautifully carved heart-shaped salt lamp. Perfect as a romantic gift or to add a touch of affection to any room. The heart shape symbolizes love while the warm glow creates an intimate atmosphere.',
  'Romantic heart-shaped lamp perfect for gifts',
  4000.00,
  4800.00,
  'salt-lamp',
  'Heart',
  'Small',
  1.8,
  40,
  true,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Display in bedrooms or living spaces. Makes an excellent gift for loved ones. Use lower wattage bulbs for a subtle, romantic glow.',
  'Delicate carved edges - handle with care. Not suitable for high-humidity areas.'
),
(
  'Bowl Salt Lamp with Chunks',
  'bowl-salt-lamp-chunks',
  'A wooden bowl filled with natural Himalayan salt chunks, illuminated from within for a stunning crystalline display. Arrange the chunks as you like for a personalized look. The multiple surfaces catch and reflect light beautifully.',
  'Wooden bowl with illuminated salt chunks for customizable display',
  3500.00,
  4200.00,
  'salt-lamp',
  'Bowl',
  'Medium',
  2.0,
  35,
  false,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Arrange chunks for different light effects. Remove chunks occasionally to clean dust. The wooden bowl adds a natural, rustic touch.',
  'Ensure the bulb does not directly touch the salt chunks. Keep the wooden bowl dry.'
),
(
  'Extra Large Natural Salt Lamp',
  'extra-large-natural-salt-lamp',
  'Make a bold statement with this impressive extra-large salt lamp. Weighing over 10kg, this magnificent piece serves as both a functional lamp and a stunning centerpiece. The substantial size means more surface area for the warm, healing glow to emanate.',
  'Statement piece for large spaces with powerful ambient glow',
  12000.00,
  14000.00,
  'salt-lamp',
  'Natural',
  'Extra Large',
  12.0,
  15,
  true,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Requires a sturdy surface due to weight. Use a 25W bulb for optimal heat and glow. Ideal for large living rooms, offices, or commercial spaces.',
  'Very heavy - handle with assistance. Ensure electrical components can handle extended use. Keep away from edges.'
),
(
  'Cylinder Salt Lamp',
  'cylinder-salt-lamp',
  'Sleek and modern, this cylindrical salt lamp adds contemporary elegance to any space. The smooth, uniform shape creates an even distribution of warm light, perfect for minimalist interiors and modern decor styles.',
  'Modern cylindrical design for contemporary spaces',
  5000.00,
  5800.00,
  'salt-lamp',
  'Cylinder',
  'Medium',
  2.8,
  28,
  false,
  ARRAY['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
  'Perfect for modern and minimalist interiors. The vertical shape saves table space while maximizing light output.',
  'Smooth surface - wipe gently with a dry cloth. Avoid using water or cleaning solutions.'
);
